baseurl = "/"
title = "Credibly Curious"
theme = "hugo-xmin"
googleAnalytics = "UA-69408097-1"
disqusShortname = "njtierney"
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3
[[menu.main]]
    name = "Talks"
    url = "/talks/"
    weight = 4
[[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 5
[[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 6
[[menu.main]]
    name = "Software"
    url = "/software/"
    weight = 6

[params]
    description = "Credibly Curious"
    GithubEdit = "https://github.com/rbind/njtierney.com/edit/master/content/"
    footer = "&copy; [Nicholas Tierney](https://njtierney.com) 2017 | [Github](https://github.com/njtierney) | [Twitter](https://twitter.com/nj_tierney)"
